#requires -Version 5.1
<#
    HackAlem AI - make a laptop ready in one command.

        pwsh -File bootstrap.ps1

    Exists because `codex exec -p hackathon` fails instantly on any laptop that does not
    have ~/.codex/hackathon.config.toml, and that file is not version controlled anywhere
    else. A teammate cloning this repo now gets the profile with it.

    Idempotent: safe to re-run. Nothing here touches the daily Codex config.
#>
[CmdletBinding()]
param(
    # Skip the live Codex round trip and the pytest run (~1 min faster, less certainty).
    [switch]$Offline
)

$ErrorActionPreference = 'Stop'
$repo        = $PSScriptRoot
$codexHome   = Join-Path $HOME '.codex'
$profilePath = Join-Path $codexHome 'hackathon.config.toml'
$parent      = Split-Path $repo -Parent
$problems    = [System.Collections.Generic.List[string]]::new()   # blocking
$notes       = [System.Collections.Generic.List[string]]::new()   # worth saying, not blocking

function Test-Cmd([string]$name) {
    [bool](Get-Command $name -ErrorAction SilentlyContinue)
}
function Ok   ([string]$m) { Write-Host "  OK    $m" -ForegroundColor Green }
function Warn ([string]$m) { Write-Host "  NOTE  $m" -ForegroundColor Yellow; $notes.Add($m) }
function Fail ([string]$m) { Write-Host "  FAIL  $m" -ForegroundColor Red;    $problems.Add($m) }

Write-Host "`nHackAlem AI bootstrap" -ForegroundColor Cyan
Write-Host "repo: $repo`n"

# --- 1. Codex profile ------------------------------------------------------------------
# Plugins off: none of them help write Python, all cost startup time and RAM.
# reasoning "high" not "ultra": measured 45s vs 2m36s on a real coding task, and per-call
# latency compounds over dozens of delegations in a five-hour race.
$profileBody = @"
# HackAlem AI - lean Codex profile. Generated by bootstrap.ps1; edit there, not here.
# Layered over ~/.codex/config.toml via:  codex exec -p hackathon "..."
# The daily config is untouched. Delete this file to revert.

model = "gpt-5.6-terra"
model_reasoning_effort = "high"

[plugins."browser@openai-bundled"]
enabled = false
[plugins."computer-use@openai-bundled"]
enabled = false
[plugins."unified-computer-use@openai-bundled"]
enabled = false
[plugins."codex-app-tools@openai-bundled"]
enabled = false
[plugins."visualize@openai-bundled"]
enabled = false
[plugins."slack@openai-curated"]
enabled = false
[plugins."google-calendar@openai-curated"]
enabled = false
[plugins."documents@openai-primary-runtime"]
enabled = false
[plugins."pdf@openai-primary-runtime"]
enabled = false
[plugins."spreadsheets@openai-primary-runtime"]
enabled = false
[plugins."presentations@openai-primary-runtime"]
enabled = false
[plugins."template-creator@openai-primary-runtime"]
enabled = false

# Trust this checkout and its parent so no approval prompt interrupts a delegated run.
# On the day the organiser's repo sits somewhere new - re-run this script from inside it.
[projects.'$repo']
trust_level = "trusted"

[projects.'$parent']
trust_level = "trusted"
"@

if (-not (Test-Path $codexHome)) {
    New-Item -ItemType Directory -Path $codexHome -Force | Out-Null
}
if ((Test-Path $profilePath) -and ((Get-Content $profilePath -Raw).TrimEnd() -eq $profileBody.TrimEnd())) {
    Ok "Codex profile already current ($profilePath)"
} else {
    if (Test-Path $profilePath) {
        Copy-Item $profilePath "$profilePath.bak" -Force
        Warn "Existing profile backed up to hackathon.config.toml.bak"
    }
    Set-Content -Path $profilePath -Value $profileBody -Encoding UTF8
    Ok "Codex profile written ($profilePath)"
}

# --- 2. Toolchain ----------------------------------------------------------------------
foreach ($t in @(
    @{ n = 'codex';  why = 'mandatory per the organisers (Regulations 8.6)' },
    @{ n = 'git';    why = 'hourly commits are the disqualification rule (6.6)' },
    @{ n = 'uv';     why = 'installs and runs the project' }
)) {
    if (Test-Cmd $t.n) { Ok "$($t.n) found" } else { Fail "$($t.n) MISSING - $($t.why)" }
}
# Driver-only; a teammate without it is fine because only the Driver deploys (lane rule 3).
if (Test-Cmd 'vercel') { Ok 'vercel found (Driver lane)' } else { Warn 'vercel not found - only the Driver needs it' }

# --- 3. Live checks --------------------------------------------------------------------
if ($Offline) {
    Warn 'Offline mode: skipped the live Codex round trip and the test run'
} else {
    if (Test-Cmd 'codex') {
        Write-Host "`n  ... testing the profile against Codex (about 15s)"
        # If Codex rejects the pinned model the whole profile is dead, and it would only
        # surface at hour zero. Catch it now and fall back to a model-free profile.
        $probe = & codex exec -p hackathon --approve-for-me -C $repo 'reply with the single word: ready' 2>&1 | Out-String
        if ($LASTEXITCODE -eq 0) {
            Ok 'Codex profile works'
        } else {
            Warn 'Codex rejected the profile - retrying without the pinned model line'
            ($profileBody -replace '(?m)^model = "gpt-5\.6-terra"\r?\n', '') |
                Set-Content -Path $profilePath -Encoding UTF8
            $probe = & codex exec -p hackathon --approve-for-me -C $repo 'reply with the single word: ready' 2>&1 | Out-String
            if ($LASTEXITCODE -eq 0) { Ok 'Codex profile works (inherited model)' }
            else { Fail "Codex profile still failing: $($probe.Trim() -split "`n" | Select-Object -First 3)" }
        }
    }
    if (Test-Cmd 'uv') {
        Write-Host "  ... installing dependencies and running the smoke suite"
        & uv sync --quiet 2>&1 | Out-Null
        $tests = & uv run pytest -q 2>&1 | Out-String
        if ($LASTEXITCODE -eq 0) { Ok "smoke suite green" } else { Fail "smoke suite RED:`n$tests" }
    }
}

# --- 4. Verdict ------------------------------------------------------------------------
Write-Host ''
if ($problems.Count -eq 0) {
    Write-Host 'READY. Read AGENTS.md, then claim your lane in PROGRESS.md.' -ForegroundColor Green
    if ($notes.Count -gt 0) {
        Write-Host "  (notes, none blocking: $($notes -join '; '))" -ForegroundColor DarkGray
    }
    exit 0
}
Write-Host "NOT READY - $($problems.Count) blocker(s):" -ForegroundColor Red
$problems | ForEach-Object { Write-Host "  - $_" }
exit 1
